### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by Goicox** [babelshift/SharpDL#2]
Dear Justin / babelshift, 

It would be really good if you could post more examples. For instance, how to draw shapes and / or handle events. 

Thank you in advance, Goicox

**Comment by babelshift** [comment]
@Goicox Thanks for the suggestion. To be honest, it's been a long time since I've really dug into this library. I will do my best to update the examples when I get the chance!

**Comment by Goicox** [comment]
Thank you in advance! Goicox

**Comment by babelshift** [comment]
Three years later, and I've finally added some examples. I'm hoping to create more as well.

- [Blank Window](https://github.com/babelshift/SharpDL/tree/master/Examples/Example1_BlankWindow)
- [Draw Texture](https://github.com/babelshift/SharpDL/tree/master/Examples/Example2_DrawTexture)
- [Event Handling](https://github.com/babelshift/SharpDL/tree/master/Examples/Example3_EventHandling)
